name:                haskell-sandbox
version:             0.1.0.0
github:              "githubuser/haskell-sandbox"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-sandbox#readme>

dependencies:
- base >= 4.7 && < 5
- hspec == 2.11.7
- QuickCheck == 2.14.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-sandbox-inspect:
    main:                Inspect.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Inspect
    dependencies:
    - haskell-sandbox
    when:
    - condition: false
      other-modules: Paths_haskell_sandbox

  haskell-sandbox-CIS194:
    main:                Cis194.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Cis194
    dependencies:
    - haskell-sandbox
    when:
    - condition: false
      other-modules: Paths_haskell_sandbox

  haskell-sandbox-sec:
    main:                Second.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Second
    dependencies:
    - haskell-sandbox
    when:
    - condition: false
      other-modules: Paths_haskell_sandbox

  haskell-sandbox-fir:
    main:                First.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is First
    dependencies:
    - haskell-sandbox
    when:
    - condition: false
      other-modules: Paths_haskell_sandbox


tests:
  haskell-sandbox-test-unit:
    main:                Spec.hs
    source-dirs:         test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sandbox

  haskell-sandbox-test-integ:
    main:                Spec.hs
    source-dirs:         test/integ
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sandbox

  haskell-sandbox-test-CIS194:
    main:                Spec.hs
    source-dirs:         test/CIS194
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-sandbox
